site_name: Jekyll Academic
pages:
- About: about.md
- Quickstart: index.md
- Documentation:
  - Documentation: documentation.md
  - Advanced Features: advanced.md
  - Additional Resources: resources.md
- Workshop: workshop.md

theme: journal
